### ISSUE TITLE
[SUGGESTION]: Pull to refresh

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#93]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to explicitly reload content in the app without having to "cold start" it.

**Describe the solution you'd like**
"Pull-to-refresh" on the main/home page (and other  pages such as crowdaction list or crowdaction details).

**Describe alternatives you've considered**
Upon returning to a page (comes to foreground) check if it hasn't been updated in a while and if this is the case, reload the content. (This might actually be less convenient and harder to implement)

**Describe or list the benefits this change would bring**
* Better usuability
* Change that user is looking at outdated content is reduced

**Additional context**
[Implementation tutorial](https://www.geeksforgeeks.org/flutter-implementing-pull-to-refresh)

**Comment by Xazin** [comment]
Let's describe the feature and the technical details a bit more so it's easier for someone to pick it up, will look at it after MVP if needed.

But sounds like a good idea to have, otherwise content can be easily outdated, and if you go to the app from a sleeping state the data won't necessarily be representative anymore.

**Comment by yasht01** [comment]
@rubenhorn Which elements of the the Details screen need to be updated for pull to refresh?

**Comment by rubenhorn** [comment]
I suppose everything that could be expected to change within a short time.
(Maybe this just encompasses the participation count and top participants?)
